04_Rails/todoes/config/routes.rb
Rails.application.routes.draw do
  root to: 'todoes#index'
  resources :todoes
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

04_Rails/todoes/app/controllers/todoes_controller.rb
class TodoesController < ApplicationController
  def index
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    todo = Todo.new(todo_params)
    todo.save!
    redirect_to todoes_url, notice: "タスク「#{todo.name}」を登録しました。"
  end

  def edit
  end

  private

  def todo_params
    params.require(:todo).permit(:name, :description)
  end
end

04_Rails/todoes/app/helpers/todoes_helper.rb
module TodoesHelper
end

04_Rails/todoes/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Todoes
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav class='uk-nav uk-nav-default uk-padding-small uk-background-primary uk-light'
      .uk-text-lead.uk-text-bold TODOES
    - if flash.notice.present?
      .uk-alert-primary
        = flash.notice
    section class='uk-container uk-container-expand uk-section'
    
      = yield

04_Rails/todoes/app/views/todoes/edit.html.slim
h1 Todoes#edit
p Find me in app/views/todoes/edit.html.slim

04_Rails/todoes/app/views/todoes/index.html.slim
h1 class='uk-text-bold' タスク一覧

= link_to '新規登録', new_todo_path, class: 'uk-button uk-button-primary uk-button-large'

04_Rails/todoes/app/views/todoes/new.html.slim
h1 class='uk-text-bold' タスクの新規登録

/ = link_to '一覧', todoes_path, class: 'uk-button uk-button-primary'

= form_with model: @todo, local: true do |f|
  .uk-margin.uk-padding-small
    = f.label :name, class: 'uk-margin-small'
    = f.text_field :name, class: 'uk-input', id: 'todo_name', placeholder: "タスク名"
  .uk-margin.uk-padding-small
    = f.label :description, class: 'uk-margin-small'
    = f.text_area :description, rows: 5, class: 'uk-textarea', id: 'todo_description', placeholder: "タスクの内容を記載してください"
  = f.submit nil, class: 'uk-button uk-button-primary uk-button-large'

04_Rails/todoes/app/views/todoes/show.html.slim
h1 Todoes#show
p Find me in app/views/todoes/show.html.slim