04_Rails/todos/config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root to: 'todos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

04_Rails/todos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

04_Rails/todos/app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :name, length: {maximum: 30}
  validate :validate_name_not_including_comma

  private

  def validate_name_not_including_comma
    errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
  end
end

04_Rails/todos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

04_Rails/todos/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo, notice: "「#{@todo.name}」を登録しました。"
    else
      render :new
    end
    
  end

  def destroy
    todo = Todo.find(params[:id])
    todo.destroy
    redirect_to todos_url, notice: "「#{todo.name}」を削除しました。"
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    todo = Todo.find(params[:id])
    todo.update!(todo_params)
    redirect_to todos_url, notice: "TODO「#{todo.name}」を更新しました。"
  end

  private

  def todo_params
    params.require(:todo).permit(:name, :description)
  end
end

04_Rails/todos/app/helpers/application_helper.rb
module ApplicationHelper
end

04_Rails/todos/app/helpers/todos_helper.rb
module TodosHelper
end

04_Rails/todos/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Todos
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header.uk-padding-small.uk-background-primary 
      = link_to 'TODOS', root_path, class: 'uk-light'
    .uk-container.uk-container-small.uk-margin
      - if flash.notice.present?
        .uk-alert.uk-alert-success= flash.notice
      = yield

04_Rails/todos/app/views/todos/_form.html.slim
- if todo.errors.present?
  ul.uk-alert.uk-alert-danger
    - todo.errors.full_messages.each do |message|
      li = message

= form_with model: todo, class: '', local: true do |f|
  .uk-margin-large
    = f.label :name
    = f.text_field :name, class: 'uk-input', id: 'todo_name'
  .uk-margin-large
    = f.label :description
    = f.text_area :description, rows: 5, class: 'uk-textarea', id: 'todo_description'
  = f.submit nil, class: 'uk-button uk-button-primary'

04_Rails/todos/app/views/todos/edit.html.slim
h1 class="uk-heading-small uk-bold uk-heading-line" Edit

= link_to '一覧', todos_path, class: 'uk-button uk-button-primary'

= render partial: 'form', locals: {todo: @todo}

04_Rails/todos/app/views/todos/index.html.slim
h1 class="uk-heading-small uk-bold uk-heading-line" TODOS

= link_to '新規登録', new_todo_path, class: 'uk-button uk-button-primary'

table.uk-table.uk-table-divider.uk-table-hover.uk-table-justify.uk-table-responsive
  thead
    tr 
      th= Todo.human_attribute_name(:name)
      th= Todo.human_attribute_name(:created_at)
      th
  tbody 
    - @todos.each do |todo|
      tr 
        td= link_to todo.name, todo_path(todo)
        td= todo.created_at
        td= link_to '編集', edit_todo_path(todo), class: 'uk-button uk-button-secondary'
        td= link_to '削除', todo, method: :delete, data: { confirm: "「#{todo.name}」を削除します。よろしいですか？" }, class: 'uk-button uk-button-default'

04_Rails/todos/app/views/todos/new.html.slim
h1 class="uk-heading-small uk-bold uk-heading-line" New

= link_to '一覧', todos_path, class: 'uk-button uk-button-primary'

= render partial: 'form', locals: {todo: @todo}

04_Rails/todos/app/views/todos/show.html.slim
h1 class="uk-heading-small uk-bold uk-heading-line" Detail

= link_to '新規登録', new_todo_path, class: 'uk-button uk-button-primary'

.uk-overflow-auto
  table.uk-table.uk-table-divider.uk-table-middle.uk-table-uk-table-responsive
    tbody 
      tr 
        th.uk-width-small= Todo.human_attribute_name(:id)
        td= @todo.id
      tr 
        th.uk-width-small= Todo.human_attribute_name(:name)
        td= @todo.name
      tr 
        th.uk-width-small= Todo.human_attribute_name(:description)
        td= simple_format(h(@todo.description), {}, sanitize: false, wrapper_tag: "div")
      tr 
        th.uk-width-small= Todo.human_attribute_name(:created_at)
        td= @todo.created_at
      tr 
        th.uk-width-small= Todo.human_attribute_name(:updated_at)
        td= @todo.updated_at
  = link_to '編集', edit_todo_path, class: 'uk-button uk-button-secondary'
  = link_to '削除', @todo, method: :delete, data: { confirm: "「#{@todo.name}」を削除します。よろしいですか？" }, class: 'uk-button uk-button-default'
  